### ISSUE TITLE
Grab diff file

### ISSUE THREAD

**Issue by hannesa2** [ewanmellor/git-diff-image#25]
I want to automate this image compare on github actions, so I want to only generate diff files, store it and don't view it.

I figured out [here](https://github.com/ewanmellor/git-diff-image/blob/master/diff-image#L249) is the file, 
`exec open "$destfile"`
but I want to prevent to change this file `diff-image` and probably there is already a command line to do this save of diff file, is there one ?

**Comment by ewanmellor** [comment]
Yes, `$destfile` is the one that you want.

No, that option does not exist in the script.  It sounds like a good idea though, so if you added it I would happily accept that pull request.

You could add a `-o` option to specify the output path, and then if that is set you would just move `$destfile` there instead of calling `exec open` or `xdg-open`.
